
export const STRINGS: any = {
    ketapangkab: {
      title: "SiCesa",
      desc: "Sistem Cepat Informasi Desa",
      nama: "SiCesa",
      kabkota: "Kabupaten Ketapang",
      slogan: "",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ketapangkab.png",
      logo_dss_url: '/img/logo/sicesa.png',
      nama_user: "Alexander Wilyo, S.STP., M.Si.",
      jabatan_user: "Bupati Ketapang",
      logo_hide: "",
      logo_first: "gap",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {
        background_color: "#0077B2",
        text_color: "#0077B2",
        btn_color: "#cddff7",
        pagination_color: '#0077B2',
        table_header_color: '#8ec5ff',
        icon_color: "#0077B2",
        nav_underline_color: '#0077B2',
        nav_underline_text_color: '#0077B2'
      }
    },
    enrekangkab: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "Desa Emas",
      kabkota: "Kabupaten Enrekang",
      slogan: "Tana Rigalla' Tana Riabussungi",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/enrekang.png",
      logo_dss_url: "https://cdn.digitaldesa.com/statics/online/homepage/img/logo_desa_emas_enrekang.svg",
      nama_user: "Dr. H. Baba, SE., MM.",
      jabatan_user: "Pj. Bupati Enrekang",
      logo_hide: "",
      logo_first: "gap",
      background_color: "#3B2D64",
      font_color: "#ffffff",
      bg_color_jumbotron: "#642ee2",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "enrekang",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {
        text_color: "#ffffff",
        btn_color: "#642ee2",
        pagination_color: ''
      },
      alternative_style: "assets/css/style.css"
    },
    luwukab: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "PENDEKAR",
      kabkota: "Kabupaten Luwu",
      slogan: "Luwu Wanua Mappatuo'e Naewai Alena, Toddo Puli Temmalara Te'bakke Tongengnge",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/luwu.png",
      logo_dss_url: "",
      nama_user: "Basmin Mattayang",
      jabatan_user: "Bupati Luwu",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {},
      alternative_style: "assets/css/alternative-style.css"
    },
    mamasakab: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "PENDEKAR",
      kabkota: "Kabupaten Mamasa",
      slogan: "Mesa Kada Dipotuo, Pantan Kada Dipomate",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/mamasakab.png",
      logo_dss_url: "",
      nama_user: "Ramlan Badawi",
      jabatan_user: "Bupati Mamasa",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "",
      menu_pengaduan: "hide",
      theme: {},
      alternative_style: "assets/css/alternative-style.css"
    },
    gowakab: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "PENDEKAR",
      kabkota: "Kabupaten Gowa",
      slogan: "Butta Patturioloang",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/gowakab.png",
      logo_dss_url: "",
      nama_user: "Adnan Purichta Ichsan",
      jabatan_user: "Bupati Gowa",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {},
      alternative_style: "assets/css/alternative-style.css"
    },
    wajokab: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "Mabello",
      kabkota: "Kabupaten Wajo",
      slogan: "Maradeka Towajoe Ade'na Napopuang",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/wajokab.png",
      logo_dss_url: "https://i.postimg.cc/XYfS3Cfp/Logo-Mabello1-removebg-preview.png",
      nama_user: "Amran Mahmud",
      jabatan_user: "Bupati Wajo",
      logo_hide: "",
      logo_first: "gap",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {
        alternative: true
      },
      alternative_style: "assets/css/alternative-style.css"
    },
    konawekab: {
      title: "SIMONI ADIK BANGDES",
      desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
      nama: "PENDEKAR",
      kabkota: "Kabupaten Konawe",
      slogan: "Berdaya saing, sejahtera, adil, dan berkelanjutan (Konawe Bersahaja)",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
      logo_dss_url: "",
      nama_user: "H. Yusran Akbar, S.T.",
      jabatan_user: "Bupati Konawe",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "",
      theme: {
        alternative: true
      },
      alternative_style: "assets/css/alternative-style.css"
    },
    ambon: {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "PENDEKAR",
      kabkota: "Kota Ambon",
      slogan: "Bersatu Manggurebe Maju",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ambon.png",
      logo_dss_url: "",
      nama_user: "PENDEKAR",
      jabatan_user: "PJ.AMBON",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {},
      alternative_style: "assets/css/alternative-style.css"
    },
    "baguala-ambon": {
      title: "PENDEKAR",
      desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
      nama: "PENDEKAR",
      kabkota: "Kecamatan Baguala",
      slogan: "Bersatu Manggurebe Maju",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ambon.png",
      logo_dss_url: "",
      nama_user: "KEC.BAGUALA",
      jabatan_user: "PJ.Kecamatan Baguala",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "hide",
      theme: {},
      alternative_style: "assets/css/alternative-style.css"
    },
    "wawotobi-konawekab": {
      title: "SIMONI ADIK BANGDES",
      desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
      nama: "PENDEKAR",
      kabkota: "Kec. Wawotobi, Kab. Konawe",
      slogan: "Konawe Harapan Rakyat",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
      logo_dss_url: "",
      nama_user: "Harmin Ramba",
      jabatan_user: "Pj.Kec Wawotobi",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "",
      theme: {
        alternative: true
      },
      alternative_style: "assets/css/alternative-style.css"
    },
    default: {
      title: "SIMONI ADIK BANGDES",
      desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
      nama: "PENDEKAR",
      kabkota: "Kec. Wawotobi, Kab. Konawe",
      slogan: "Konawe Harapan Rakyat",
      logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
      logo_dss_url: "",
      nama_user: "Harmin Ramba",
      jabatan_user: "Pj.Kec Wawotobi",
      logo_hide: "hide",
      logo_first: "",
      background_color: "#327A6E",
      font_color: "#ffffff",
      bg_color_jumbotron: "#327A6E",
      font_color_jumbotron: "#ffffff",
      logo_second_size: "",
      menu_pelayanan: "hide",
      menu_pengaduan: "",
      theme: {
        alternative: true
      },
      alternative_style: "assets/css/alternative-style.css"
    }
  };
