import defaultUser from '../assets/profil/default.png'
import { CDN_URL } from './api';

export const STRINGS: any = {
  digikab: {
    title: "SiCesa",
    desc: "Sistem Cepat Informasi Desa",
    nama: "SiCesa",
    kabkota: "Kabupaten Ketapang",
    slogan: "",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/ketapangkab.png",
    logo_dss_url: '/img/logo/sicesa.png',
    logo_background_image_login: 'ketapangkab.jpeg',
    nama_user: "Alexander Wilyo, S.STP., M.Si.",
    jabatan_user: "Bupati Ketapang",
    nama_user_2: "Jamhuri Amir, S.H.",
    logo_user: defaultUser,
    logo_user_2: "/img/wakil.png",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#0077B2",
      color_normal: "#8ec5ff",
      color_light: "#cddff7",
      text_color: "#ffffff",
    }
  },
  ketapangkab: {
    title: "SiCesa",
    desc: "Sistem Cepat Informasi Desa",
    nama: "SiCesa",
    kabkota: "Kabupaten Ketapang",
    slogan: "",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/ketapangkab.png",
    logo_dss_url: '/img/logo/sicesa.png',
    logo_background_image_login: 'ketapangkab.jpeg',
    nama_user: "Alexander Wilyo, S.STP., M.Si.",
    jabatan_user: "Bupati Ketapang",
    nama_user_2: "Jamhuri Amir, S.H.",
    logo_user: defaultUser,
    logo_user_2: "/img/wakil.png",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#0077B2",
      color_normal: "#8ec5ff",
      color_light: "#cddff7",
      text_color: "#ffffff",
    }
  },
  enrekangkab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "Desa Emas",
    kabkota: "Kabupaten Enrekang",
    slogan: "Tana Rigalla' Tana Riabussungi",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/enrekang.png",
    logo_dss_url: CDN_URL + "statics/online/homepage/img/logo_desa_emas_enrekang.svg",
    logo_background_image_login: 'enrekangkab.png',
    nama_user: "H. Muh. Yusuf Ritangnga",
    nama_user_2: "",
    jabatan_user: "Bupati Enrekang",
    jabatan_user_2: "",
    logo_user: defaultUser,
    logo_user_2: "",
    font_color: "#ffffff",
    bg_color_jumbotron: "#642ee2",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    alternative_style: "assets/css/style.css",
    theme: {
      color_deep: "#6b1fd1",
      color_normal: "#6D3764",
      color_light: "#CFA0C7",
      text_color: "#ffffff",

    },
  },
  luwukab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Luwu",
    slogan: "Luwu Wanua Mappatuo'e Naewai Alena, Toddo Puli Temmalara Te'bakke Tongengnge",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/luwu.png",
    logo_dss_url: "",
    logo_background_image_login: 'luwukab.jpg',

    nama_user: "Basmin Mattayang",
    jabatan_user: "Bupati Luwu",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  mamasakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Mamasa",
    slogan: "Mesa Kada Dipotuo, Pantan Kada Dipomate",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/mamasakab.png",
    logo_dss_url: "",
    logo_background_image_login: 'mamasakab.jpg',

    nama_user: "Ramlan Badawi",
    jabatan_user: "Bupati Mamasa",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  gowakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Gowa",
    slogan: "Butta Patturioloang",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/gowakab.png",
    logo_dss_url: "",
    logo_background_image_login: 'gowakab.jpg',

    nama_user: "Adnan Purichta Ichsan",
    jabatan_user: "Bupati Gowa",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  wajokab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "Mabello",
    kabkota: "Kabupaten Wajo",
    slogan: "Maradeka Towajoe Ade'na Napopuang",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/wajokab.png",
    logo_dss_url: "https://i.postimg.cc/XYfS3Cfp/Logo-Mabello1-removebg-preview.png",
    logo_background_image_login: 'wajokab.jpg',

    nama_user: "Amran Mahmud",
    jabatan_user: "Bupati Wajo",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  konawekab: {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Konawe",
    slogan: "Berdaya saing, sejahtera, adil, dan berkelanjutan (Konawe Bersahaja)",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: 'konawekab.jpg',

    nama_user: "H. Yusran Akbar, S.T.",
    jabatan_user: "Bupati Konawe",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  ambon: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kota Ambon",
    slogan: "Bersatu Manggurebe Maju",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/ambon.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "PENDEKAR",
    jabatan_user: "PJ.AMBON",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  "baguala-ambon": {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kecamatan Baguala",
    slogan: "Bersatu Manggurebe Maju",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/ambon.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "KEC.BAGUALA",
    jabatan_user: "PJ.Kecamatan Baguala",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  "wawotobi-konawekab": {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kec. Wawotobi, Kab. Konawe",
    slogan: "Konawe Harapan Rakyat",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "Harmin Ramba",
    jabatan_user: "Pj.Kec Wawotobi",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  "rengasdengklok-karawangkab": {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kecamatan Rengasdengklok",
    slogan: "",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/karawang.png",
    logo_dss_url: "",
    logo_background_image_login: 'rengasdengklok.png',
    nama_user: "KEC. RENGASDENGKLOK",
    jabatan_user: "Camat Rengasdengklok",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  default: {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kec. Wawotobi, Kab. Konawe",
    slogan: "Konawe Harapan Rakyat",
    logo_kab_url: CDN_URL + "uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: '',
    nama_user: "Harmin Ramba",
    jabatan_user: "Pj.Kec Wawotobi",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      color_deep: "#327A6E",
      color_normal: "#0cceae",
      color_light: "#91EFF3",
      text_color: "#ffffff",
    },
    alternative_style: "assets/css/alternative-style.css"
  }
};
