import defaultUser from '../assets/profil/default.png'


export const STRINGS: any = {
  ketapangkab: {
    title: "SiCesa",
    desc: "Sistem Cepat Informasi Desa",
    nama: "SiCesa",
    kabkota: "Kabupaten Ketapang",
    slogan: "",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ketapangkab.png",
    logo_dss_url: '/img/logo/sicesa.png',
    logo_background_image_login: 'ketapangkab.jpeg',
    nama_user: "Alexander Wilyo, S.STP., M.Si.",
    jabatan_user: "Bupati Ketapang",
    logo_user: defaultUser,
    logo_user_2: "/img/wakil.png",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#0077B2",
      text_color: "#0077B2",
      btn_color: "#cddff7",
      pagination_color: '#0077B2',
      table_header_color: '#8ec5ff',
      icon_color: "#0077B2",
      nav_underline_color: '#0077B2',
      nav_underline_text_color: '#0077B2'
    }
  },
  enrekangkab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "Desa Emas",
    kabkota: "Kabupaten Enrekang",
    slogan: "Tana Rigalla' Tana Riabussungi",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/enrekang.png",
    logo_dss_url: "https://cdn.digitaldesa.com/statics/online/homepage/img/logo_desa_emas_enrekang.svg",
    logo_background_image_login: 'enrekangkab.jpg',
    nama_user: "Dr. H. Baba, SE., MM.",
    nama_user_2: "",
    jabatan_user: "Pj. Bupati Enrekang",
    jabatan_user_2: "",
    logo_user: defaultUser,
    logo_user_2: "",
    font_color: "#ffffff",
    bg_color_jumbotron: "#642ee2",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    alternative_style: "assets/css/style.css",
    theme: {
      background_color: "#3B2D64",
      text_color: "#ffffff",
      btn_color: "#3B2D64",
      pagination_color: '#3B2D64',
      table_header_color: '#3B2D64',
      icon_color: "#3B2D64",
      nav_underline_color: '#3B2D64',
      nav_underline_text_color: '#3B2D64',
    },
  },
  luwukab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Luwu",
    slogan: "Luwu Wanua Mappatuo'e Naewai Alena, Toddo Puli Temmalara Te'bakke Tongengnge",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/luwu.png",
    logo_dss_url: "",
    logo_background_image_login: 'luwukab.jpg',

    nama_user: "Basmin Mattayang",
    jabatan_user: "Bupati Luwu",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  mamasakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Mamasa",
    slogan: "Mesa Kada Dipotuo, Pantan Kada Dipomate",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/mamasakab.png",
    logo_dss_url: "",
    logo_background_image_login: 'mamasakab.jpg',

    nama_user: "Ramlan Badawi",
    jabatan_user: "Bupati Mamasa",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  gowakab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Gowa",
    slogan: "Butta Patturioloang",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/gowakab.png",
    logo_dss_url: "",
    logo_background_image_login: 'gowakab.jpg',

    nama_user: "Adnan Purichta Ichsan",
    jabatan_user: "Bupati Gowa",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  wajokab: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "Mabello",
    kabkota: "Kabupaten Wajo",
    slogan: "Maradeka Towajoe Ade'na Napopuang",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/wajokab.png",
    logo_dss_url: "https://i.postimg.cc/XYfS3Cfp/Logo-Mabello1-removebg-preview.png",
    logo_background_image_login: 'wajokab.jpg',

    nama_user: "Amran Mahmud",
    jabatan_user: "Bupati Wajo",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  konawekab: {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kabupaten Konawe",
    slogan: "Berdaya saing, sejahtera, adil, dan berkelanjutan (Konawe Bersahaja)",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: 'konawekab.jpg',

    nama_user: "H. Yusran Akbar, S.T.",
    jabatan_user: "Bupati Konawe",
    logo_user: defaultUser,
    nama_user_2: "",
    jabatan_user_2: "",
    logo_user_2: "",

    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#ffffff",
      pagination_color: '#0077B2',
      table_header_color: '#8ec5ff',
      icon_color: "#0077B2",
      nav_underline_color: '#0077B2',
      nav_underline_text_color: '#0077B2',
      alternative: true
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  ambon: {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kota Ambon",
    slogan: "Bersatu Manggurebe Maju",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ambon.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "PENDEKAR",
    jabatan_user: "PJ.AMBON",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  "baguala-ambon": {
    title: "PENDEKAR",
    desc: "Pemantauan Desa dan Kelurahan Terintegrasi",
    nama: "PENDEKAR",
    kabkota: "Kecamatan Baguala",
    slogan: "Bersatu Manggurebe Maju",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/ambon.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "KEC.BAGUALA",
    jabatan_user: "PJ.Kecamatan Baguala",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "hide",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  "wawotobi-konawekab": {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kec. Wawotobi, Kab. Konawe",
    slogan: "Konawe Harapan Rakyat",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: 'ambon.png',
    nama_user: "Harmin Ramba",
    jabatan_user: "Pj.Kec Wawotobi",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  },
  default: {
    title: "SIMONI ADIK BANGDES",
    desc: "Sistem Informasi Monitoring Administrasi Kinerja Pembangunan Desa",
    nama: "PENDEKAR",
    kabkota: "Kec. Wawotobi, Kab. Konawe",
    slogan: "Konawe Harapan Rakyat",
    logo_kab_url: "https://cdn.digitaldesa.com/uploads/landing/logo-desa/konawekab.png",
    logo_dss_url: "",
    logo_background_image_login: '',
    nama_user: "Harmin Ramba",
    jabatan_user: "Pj.Kec Wawotobi",
    background_color: "#327A6E",
    font_color: "#ffffff",
    bg_color_jumbotron: "#327A6E",
    font_color_jumbotron: "#ffffff",
    menu_pelayanan: "hide",
    menu_pengaduan: "",
    theme: {
      background_color: "#327A6E",
      text_color: "#327A6E",
      btn_color: "#D2EFE9",
      pagination_color: "#327A6E",
      table_header_color: "#8FD6C7",
      icon_color: "#327A6E",
      nav_underline_color: "#327A6E",
      nav_underline_text_color: "#327A6E"
    },
    alternative_style: "assets/css/alternative-style.css"
  }
};
